version: "3"
services:
  frontend:
    build: front-end/
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: back-end/
    restart: on-failure
    ports:
      - 8080:8080
