version: "3"
services:
  frontend:
    build: front-end/
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 8080 -w db.json
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./back-end:/data
    restart: unless-stopped
